/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RemindRouteImport } from './routes/remind'
import { Route as ResultRouteImport } from './routes/result'
import { Route as SRouteImport } from './routes/s'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as UnequalRouteImport } from './routes/unequal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindRoute = RemindRouteImport.update({
  id: '/remind',
  path: '/remind',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const SRoute = SRouteImport.update({
  id: '/s',
  path: '/s',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const UnequalRoute = UnequalRouteImport.update({
  id: '/unequal',
  path: '/unequal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/items': typeof ItemsRoute
  '/more': typeof MoreRoute
  '/profile': typeof ProfileRoute
  '/remind': typeof RemindRoute
  '/result': typeof ResultRoute
  '/s': typeof SRoute
  '/scan': typeof ScanRoute
  '/unequal': typeof UnequalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/items': typeof ItemsRoute
  '/more': typeof MoreRoute
  '/profile': typeof ProfileRoute
  '/remind': typeof RemindRoute
  '/result': typeof ResultRoute
  '/s': typeof SRoute
  '/scan': typeof ScanRoute
  '/unequal': typeof UnequalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/items': typeof ItemsRoute
  '/more': typeof MoreRoute
  '/profile': typeof ProfileRoute
  '/remind': typeof RemindRoute
  '/result': typeof ResultRoute
  '/s': typeof SRoute
  '/scan': typeof ScanRoute
  '/unequal': typeof UnequalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/friends'
    | '/history'
    | '/home'
    | '/items'
    | '/more'
    | '/profile'
    | '/remind'
    | '/result'
    | '/s'
    | '/scan'
    | '/unequal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/friends'
    | '/history'
    | '/home'
    | '/items'
    | '/more'
    | '/profile'
    | '/remind'
    | '/result'
    | '/s'
    | '/scan'
    | '/unequal'
  id:
    | '__root__'
    | '/'
    | '/friends'
    | '/history'
    | '/home'
    | '/items'
    | '/more'
    | '/profile'
    | '/remind'
    | '/result'
    | '/s'
    | '/scan'
    | '/unequal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRoute: typeof FriendsRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  ItemsRoute: typeof ItemsRoute
  MoreRoute: typeof MoreRoute
  ProfileRoute: typeof ProfileRoute
  RemindRoute: typeof RemindRoute
  ResultRoute: typeof ResultRoute
  SRoute: typeof SRoute
  ScanRoute: typeof ScanRoute
  UnequalRoute: typeof UnequalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remind': {
      id: '/remind'
      path: '/remind'
      fullPath: '/remind'
      preLoaderRoute: typeof RemindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s': {
      id: '/s'
      path: '/s'
      fullPath: '/s'
      preLoaderRoute: typeof SRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unequal': {
      id: '/unequal'
      path: '/unequal'
      fullPath: '/unequal'
      preLoaderRoute: typeof UnequalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRoute: FriendsRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  ItemsRoute: ItemsRoute,
  MoreRoute: MoreRoute,
  ProfileRoute: ProfileRoute,
  RemindRoute: RemindRoute,
  ResultRoute: ResultRoute,
  SRoute: SRoute,
  ScanRoute: ScanRoute,
  UnequalRoute: UnequalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
